
# order matters!!!
# define current directory relative to ~source
CURR_DIR = com\addval\utils\fileupload

!INCLUDE $(COMMON_CLIENT_HOME)\source\common.mk

OBJ_LIST=\
$(COMMON_OBJ_DIR)\*.class\

# $(COMMON_OBJ_DIR)\FileUpload.class\
# $(COMMON_OBJ_DIR)\FileAction.class\

all: $(OBJ_LIST)

clean:
	del /q $(OBJ_LIST)
