
# order matters!!!
# define current directory relative to ~source
CURR_DIR = com\addval\ejbutils\utils

!INCLUDE $(COMMON_CLIENT_HOME)\source\common.mk

OBJ_LIST=\
$(COMMON_OBJ_DIR)\EJBXGeneral.class\
$(COMMON_OBJ_DIR)\EJBXRuntime.class\
$(COMMON_OBJ_DIR)\EJBXFeatureNotImplemented.class\

all: $(OBJ_LIST)

clean:
	del /q $(OBJ_LIST)
