
# order matters!!!
# define current directory relative to ~source
CURR_DIR = com\addval\ejbutils\metadata

!INCLUDE $(COMMON_CLIENT_HOME)\source\common.mk

OBJ_LIST=\
$(COMMON_OBJ_DIR)\EJBUIMetaData.class\

all: $(OBJ_LIST)

cleanupjava:
	del /q *.jv~
	
clean:
	del /q $(OBJ_LIST)
